spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.17.0.2:3307/education_system?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

test: hello dev